name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  conventional-commit:
    name: Validate Commits
    uses: Peralta-CashFlow/CashFlow-WorkFlows/.github/workflows/conventional-commit-v1.yml@main
    permissions:
      contents: read
      pull-requests: write